# NumPy: Arrays

In [1]:
# pip install numpy

import numpy as np


In [2]:
def display_array_details(arr):
    print(type(arr))
    print("Dimensions:", arr.ndim)
    print("Shape:", arr.shape)


### One Dimensional Array

In [3]:
arr = np.array([1, 2, 3, 4, 5])
display_array_details(arr)
print("\nArray:", arr)

print()
for x in np.nditer(arr):
    print(x, end=' ')


<class 'numpy.ndarray'>
Dimensions: 1
Shape: (5,)

Array: [1 2 3 4 5]

1 2 3 4 5 

### Multi-Dimensional Arrays

### Two-Dimensional Array

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

"""
[
	[1, 2, 3], 
	[4, 5, 6]
]
"""

display_array_details(arr)
print("\nArray:\n", arr)

print()
for row in arr:
    for value in row:
        print(value, end=' ')


<class 'numpy.ndarray'>
Dimensions: 2
Shape: (2, 3)

Array:
 [[1 2 3]
 [4 5 6]]

1 2 3 4 5 6 

### Three-Dimensional Array

In [5]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

"""
[
	[
		[1, 2, 3], 
		[4, 5, 6]
	], 
	[
		[7, 8, 9], 
		[10, 11, 12]
	]
]
"""


display_array_details(arr)
print("\nArray:\n", arr)

print()
for matrix in arr:
    for row in matrix:
        for value in row:
            print(value, end=' ')


<class 'numpy.ndarray'>
Dimensions: 3
Shape: (2, 2, 3)

Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

1 2 3 4 5 6 7 8 9 10 11 12 

## Array Slicing

### One Dimension Array


In [6]:
# Create a numpy array with 100 random data points from 1 to 100
arr = np.random.randint(1, 101, size=100)
display_array_details(arr)
sorted_arr = np.sort(arr)

print("\nOriginal array:\n", arr)
print("\nSorted array:\n", sorted_arr)

# Slice: first 10 elements
print("\nFirst 10 elements:\n", sorted_arr[:10])

# Slice: last 10 elements
print("\nLast 10 elements:\n", sorted_arr[-10:])

# Slice: every 5th element
print("\nEvery 5th element:\n", sorted_arr[::5])

# Slice: elements from index 25 to 50
print("\nElements from index 25 to 50:\n", sorted_arr[25:51])


<class 'numpy.ndarray'>
Dimensions: 1
Shape: (100,)

Original array:
 [72  8 59 25  5 73 95 68 38 87 79 42 94 74 84 57 71  4  3  1 86 82  6 92
 97 86  8 35  5 51 53 48 50 51 68  7 70 79 19 88 18 81 48 80 79 65 83 94
 75 45  6 63 38 87 90 51 86 50  7 36 97 27 99 58 60  2 78 45 52 44 71 43
 46 15 55 35 10 86 67 18 67 30 14 69 64 10 21 15 96 76 50 85 86 86 20 32
 61 28 21 38]

Sorted array:
 [ 1  2  3  4  5  5  6  6  7  7  8  8 10 10 14 15 15 18 18 19 20 21 21 25
 27 28 30 32 35 35 36 38 38 38 42 43 44 45 45 46 48 48 50 50 50 51 51 51
 52 53 55 57 58 59 60 61 63 64 65 67 67 68 68 69 70 71 71 72 73 74 75 76
 78 79 79 79 80 81 82 83 84 85 86 86 86 86 86 86 87 87 88 90 92 94 94 95
 96 97 97 99]

First 10 elements:
 [1 2 3 4 5 5 6 6 7 7]

Last 10 elements:
 [88 90 92 94 94 95 96 97 97 99]

Every 5th element:
 [ 1  5  8 15 20 28 36 43 48 51 55 61 67 71 75 79 84 86 88 95]

Elements from index 25 to 50:
 [28 30 32 35 35 36 38 38 38 42 43 44 45 45 46 48 48 50 50 50 51 51 51 52
 53 55]


### Multi-Dimensional Array

In [7]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
display_array_details(arr)

print()
for i, a in enumerate(arr):
    print(f"{i}: {a}")

print(f"\narr[0:2]:\n{arr[0:2]}")

print(f"\narr[1:]:\n{arr[1:]}")

print(f"\narr[0:1, 0]: {arr[0:1, 0]}")
print(f"arr[0:1, 1]: {arr[0:2, 1]}")
print(f"arr[0:1, 2]: {arr[0:3, 2]}")

print(f"\narr[1, 1]: {arr[1, 1]}")
print(f"arr[2, 2]: {arr[2, 2]}")


<class 'numpy.ndarray'>
Dimensions: 2
Shape: (3, 3)

0: [0 1 2]
1: [3 4 5]
2: [6 7 8]

arr[0:2]:
[[0 1 2]
 [3 4 5]]

arr[1:]:
[[3 4 5]
 [6 7 8]]

arr[0:1, 0]: [0]
arr[0:1, 1]: [1 4]
arr[0:1, 2]: [2 5 8]

arr[1, 1]: 4
arr[2, 2]: 8


## Random Numbers

### Integers

In [8]:
rand_nbrs = []
min_indx = 1
max_indx = 101

for i in range(min_indx, max_indx):
    rand_nbr = np.random.randint(26) # 0 - 25
    rand_nbrs.append(rand_nbr)
rand_nbrs = np.sort(rand_nbrs)
print("Sorted numbers:", rand_nbrs)

print()
rand_nbrs = []
for i in range(min_indx, max_indx):
    rand_nbr = np.random.randint(25, 51)
    rand_nbrs.append(rand_nbr)
rand_nbrs = np.sort(rand_nbrs)
print("Sorted numbers:", rand_nbrs)


# Convert from List to np Array
print()
arr = np.array(rand_nbrs)
display_array_details(arr)
print(arr)

# Reshape Array
print()
arr = arr.reshape(2, 50)
display_array_details(arr)
print(arr)

print()
arr = arr.reshape(4, 25)
display_array_details(arr)
print(arr)

print()
rand_nbrs = np.random.randint(25, 51, size=(3, 3)) # 3 rows, 3 cols
print(rand_nbrs)

# Convert n-dim Array to one-dim
print()
rand_nbrs = rand_nbrs.ravel()
print(rand_nbrs)


Sorted numbers: [ 0  0  2  2  2  2  2  3  3  3  3  3  3  4  4  4  4  5  5  5  7  7  7  7
  7  7  8  8  9  9  9  9  9 10 10 10 10 10 11 11 11 11 11 11 12 12 12 13
 13 13 13 14 14 14 14 14 15 15 15 15 16 16 16 16 16 17 17 17 17 17 17 18
 18 18 19 20 20 20 20 21 21 21 21 22 22 22 23 23 23 23 23 24 24 24 24 24
 24 25 25 25]

Sorted numbers: [25 25 26 26 26 27 27 28 28 28 28 28 29 29 30 30 30 30 30 30 30 31 31 31
 31 31 31 31 32 32 32 32 33 33 33 33 33 34 34 35 35 35 35 35 36 36 36 36
 36 36 37 37 37 37 37 37 37 37 38 38 39 39 39 39 40 40 40 40 40 40 41 41
 41 41 42 43 43 43 44 44 45 45 45 45 45 45 47 47 48 48 48 48 48 49 49 49
 49 50 50 50]

<class 'numpy.ndarray'>
Dimensions: 1
Shape: (100,)
[25 25 26 26 26 27 27 28 28 28 28 28 29 29 30 30 30 30 30 30 30 31 31 31
 31 31 31 31 32 32 32 32 33 33 33 33 33 34 34 35 35 35 35 35 36 36 36 36
 36 36 37 37 37 37 37 37 37 37 38 38 39 39 39 39 40 40 40 40 40 40 41 41
 41 41 42 43 43 43 44 44 45 45 45 45 45 45 47 47 48 48 48 48 48 49 49 49
 49 50 50 

### Uniform Distribution

In [9]:
arr = np.random.rand(10) # 10 random Floats (0 - 1)
display_array_details(arr)
print(arr)

print()

arr = np.random.rand(3, 3)
display_array_details(arr)
print(arr)


<class 'numpy.ndarray'>
Dimensions: 1
Shape: (10,)
[0.85507251 0.28416946 0.57028663 0.37896073 0.81215822 0.8224897
 0.62011052 0.20030361 0.3092963  0.83357057]

<class 'numpy.ndarray'>
Dimensions: 2
Shape: (3, 3)
[[0.71445335 0.78556129 0.93712763]
 [0.34432821 0.90384783 0.6463385 ]
 [0.19751981 0.26015909 0.38374869]]


### Standard Normal Distribution (μ is = 0, sd = 1)

In [10]:
arr = np.random.randn(3, 3) 
display_array_details(arr)
print(arr)


<class 'numpy.ndarray'>
Dimensions: 2
Shape: (3, 3)
[[ 0.12897287 -0.43441115  1.87274532]
 [ 0.34400056 -0.33290709 -1.2505359 ]
 [ 0.58596668 -0.21945411 -0.16793846]]
