# NumPy: Math

In [1]:
import numpy as np


In [2]:
def display_array_details(arr):
    print(type(arr))
    print("Dimensions:", arr.ndim)
    print("Shape:", arr.shape)


## Addition / Subtraction

In [3]:
list_1 = [1, 3, 5]
arr1 =  np.array(list_1)
display_array_details(arr1)
print(arr1)

print()
list_2 = [2, 4, 6]
arr2 =  np.array(list_2)
display_array_details(arr2)
print(arr2)

print()
arr3 = arr1 + arr2
display_array_details(arr3)
print(arr3)

print()
arr4 = arr2 - arr1
display_array_details(arr4)
print(arr4)


<class 'numpy.ndarray'>
Dimensions: 1
Shape: (3,)
[1 3 5]

<class 'numpy.ndarray'>
Dimensions: 1
Shape: (3,)
[2 4 6]

<class 'numpy.ndarray'>
Dimensions: 1
Shape: (3,)
[ 3  7 11]

<class 'numpy.ndarray'>
Dimensions: 1
Shape: (3,)
[1 1 1]


## Multiplication / Division

In [4]:
list_1 = [4, 9, 16]
arr1 =  np.array(list_1)
display_array_details(arr1)
print(arr1)

print()
list_2 = [2, 3, 4]
arr2 =  np.array(list_2)
display_array_details(arr2)
print(arr2)

print()
arr3 = arr1 * arr2
display_array_details(arr3)
print(arr3)

print()
arr4 = arr1 / arr2
display_array_details(arr4)
print(arr4)


<class 'numpy.ndarray'>
Dimensions: 1
Shape: (3,)
[ 4  9 16]

<class 'numpy.ndarray'>
Dimensions: 1
Shape: (3,)
[2 3 4]

<class 'numpy.ndarray'>
Dimensions: 1
Shape: (3,)
[ 8 27 64]

<class 'numpy.ndarray'>
Dimensions: 1
Shape: (3,)
[2. 3. 4.]


## Universal Functions (ufunct)

In [5]:
print(f"The square root of 4 is {np.sqrt(4)}")

arr = np.array([4, 9, 16])
print(f"The square roots of {arr} are {np.sqrt(arr)}")


The square root of 4 is 2.0
The square roots of [ 4  9 16] are [2. 3. 4.]


In [6]:
print(f"4 ^ 2 is {np.power(4, 2)}")

arr = np.array([2, 3, 4])
print(f"The powers of {arr} are {np.power(arr, 2)}")
print(f"Exponentials of {arr2} are {np.exp(arr2)}")


4 ^ 2 is 16
The powers of [2 3 4] are [ 4  9 16]
Exponentials of [2 3 4] are [ 7.3890561  20.08553692 54.59815003]
